"""
strategies/base_strategy.py
Abstract base class for all options-buying strategies.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Signal:
    """
    Represents a trade signal generated by a strategy.
    All signals are options BUY signals (long CE or PE).
    """
    underlying: str           # e.g. "NIFTY"
    option_type: str          # "CE" or "PE"
    strategy_name: str
    confidence: float         # 0.0 – 1.0
    sl_pct: float             # Stop loss % of option premium
    target_pct: float         # Target % of option premium
    reason: str               # Human-readable reason for the signal

    # Resolved after option chain lookup
    trading_symbol: str = ""  # e.g. NIFTY28FEB24C21900
    token: str = ""
    strike: int = 0
    expiry: str = ""
    ltp: float = 0.0          # Option premium at signal time

    # Derived risk levels (set by risk manager)
    sl_price: float = 0.0
    target_price: float = 0.0

    def __post_init__(self) -> None:
        assert 0.0 <= self.confidence <= 1.0, "Confidence must be 0–1"
        assert self.option_type.upper() in ("CE", "PE"), "option_type must be CE or PE"
        self.option_type = self.option_type.upper()

    def is_valid(self) -> bool:
        return bool(self.trading_symbol and self.ltp > 0)

    def __repr__(self) -> str:
        return (
            f"<Signal {self.strategy_name} | {self.underlying} {self.option_type} "
            f"strike={self.strike} conf={self.confidence:.2f} | {self.reason[:60]}>"
        )


class BaseStrategy(ABC):
    """
    Base class for all options buying strategies.
    Each strategy must implement generate_signal().
    """

    name: str = "base"

    @abstractmethod
    def generate_signal(self, snapshot: dict) -> Optional[Signal]:
        """
        Evaluate market data and return a Signal if conditions are met.
        
        Args:
            snapshot: Dict from MarketDataEngine.get_market_snapshot()
                Keys: symbol, token, ltp, df_5min, df_15min, df_daily,
                      prev_day_high, prev_day_low, timestamp

        Returns:
            Signal if a trade opportunity is found, None otherwise.
        """
        ...

    def _safe_last(self, df, col: str, default=float("nan")):
        """Safely get the last row value of a column from a DataFrame."""
        try:
            if df is None or df.empty or col not in df.columns:
                return default
            val = df[col].iloc[-1]
            return float(val) if val == val else default  # NaN check
        except Exception:
            return default
