"""
storage/models.py
SQLAlchemy ORM models for trades, signals, and daily PnL.
"""
from datetime import datetime
from sqlalchemy import (
    Column, Integer, Float, String, Boolean, DateTime, Date, Text
)
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass


class Trade(Base):
    """Represents a single options trade (entry to exit)."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, index=True)       # e.g. NIFTY28FEB24C21900
    underlying = Column(String(20), nullable=False)               # e.g. NIFTY
    strategy = Column(String(50), nullable=False)                 # strategy name
    option_type = Column(String(2), nullable=False)               # CE or PE
    strike = Column(Float, nullable=False)
    expiry = Column(String(20), nullable=True)
    action = Column(String(5), nullable=False)                    # BUY
    quantity = Column(Integer, nullable=False)
    lot_size = Column(Integer, nullable=False)

    entry_price = Column(Float, nullable=False)
    sl_price = Column(Float, nullable=True)
    target_price = Column(Float, nullable=True)
    exit_price = Column(Float, nullable=True)

    entry_order_id = Column(String(50), nullable=True)
    exit_order_id = Column(String(50), nullable=True)

    pnl = Column(Float, nullable=True)                            # realized PnL
    pnl_pct = Column(Float, nullable=True)                        # % return on premium
    is_paper = Column(Boolean, nullable=False, default=True)
    status = Column(String(20), nullable=False, default="OPEN")   # OPEN, CLOSED, SL_HIT, TARGET_HIT, EXPIRED, MANUAL_EXIT

    confidence = Column(Float, nullable=True)
    signal_id = Column(Integer, nullable=True)

    entry_time = Column(DateTime, default=datetime.utcnow, nullable=False)
    exit_time = Column(DateTime, nullable=True)
    notes = Column(Text, nullable=True)

    def __repr__(self) -> str:
        return (
            f"<Trade id={self.id} {self.action} {self.symbol} "
            f"qty={self.quantity} status={self.status} pnl={self.pnl}>"
        )


class Signal(Base):
    """Represents a raw signal generated by any strategy."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, index=True)
    underlying = Column(String(20), nullable=False)
    strategy = Column(String(50), nullable=False)
    option_type = Column(String(2), nullable=False)               # CE or PE
    strike = Column(Float, nullable=False)
    action = Column(String(5), nullable=False)                    # BUY
    confidence = Column(Float, nullable=False)
    sl_pct = Column(Float, nullable=True)
    target_pct = Column(Float, nullable=True)
    was_traded = Column(Boolean, default=False)
    skip_reason = Column(String(200), nullable=True)
    generated_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    def __repr__(self) -> str:
        return (
            f"<Signal {self.strategy} {self.option_type} {self.underlying} "
            f"conf={self.confidence:.2f} traded={self.was_traded}>"
        )


class DailyPnL(Base):
    """End-of-day PnL summary."""
    __tablename__ = "daily_pnl"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(Date, nullable=False, unique=True, index=True)
    realized_pnl = Column(Float, default=0.0)
    unrealized_pnl = Column(Float, default=0.0)
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    signals_generated = Column(Integer, default=0)
    is_paper = Column(Boolean, default=True)
    notes = Column(Text, nullable=True)

    def __repr__(self) -> str:
        return f"<DailyPnL {self.date} pnl={self.realized_pnl + self.unrealized_pnl:.2f}>"
